### ISSUE TITLE
How to view all subjects on one Jetstream?

### ISSUE THREAD

**Issue by intfish123** [nats-io/nats-box#40]
I use `nats str info`, and it just print informastions like this:
```
Configuration:

             Subjects: app.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 3
...
``` 
How to kown `app.*` contains how many subjects?
